[build]
publish = "exampleSiteMultilingual/public"
command = "cd exampleSiteMultilingual && hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.115.4"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "cd exampleSiteMultilingual &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
