matrix:
- name: Posts
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - :matches(code, pre)
      - span:matches(.text-muted)
      - code
      - pre
      - blockquote
  sources:
  - 'content/posts/*.md'
  default_encoding: utf-8