matrix:
- name: Posts
  aspell:
    lang: en
    d: en_US
    ignore-case: true
  dictionary:
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - :matches(code, pre)
      - b:matches(.post_date)
      - b:matches(.post_author)
      - span:matches(.post_tag)
      - code
      - pre
      - blockquote
  sources:
  - 'public/posts/*.html'
  default_encoding: utf-8