languageCode = "en-us"
baseUrl = ""
title = "Blog"
theme = "anubis"
paginate = 10
enableRobotsTXT = true

[taxonomies]
	author = "author"
	tag = "tags"
	category = "categories"

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = 0

[[menu.main]]
identifier = "about"
name = "About us"
title = "About us"
url = "/about/"
weight = 0

[params]
  author = "Wyll.io"
  email = "contact@wyll.io" # used for microformats
  avatar = "" # used for microformats
  description = ""
	style = "dark"

	[[params.social]]
  id = "linkedin"
  name = "company/wyll"

[deployment]

[[deployment.targets]]
name = "io.wyll.blog"
URL = "s3://io.wyll.blog?region=eu-west-3"
cloudFrontDistributionID = "EP96Y0H6JFISB"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true