baseurl = "https://blog.wyll.io"
languageCode = "fr"
title = "Wyll.io | Blog"
disqusShortname = "blogwyllio"
googleAnalytics = "blogwyllio"

[taxonomies]
	author = "author"
	tag = "tags"
	category = "categories"

[deployment]

[[deployment.targets]]
name = "blog.wyll.io"
URL = "s3://io.wyll.blog?region=eu-west-3"
cloudFrontDistributionID = "E49UL545A0LIH"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true