name: Spelling

on:
  pull_request:
  push:
    branches: [dev, master]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - uses: rojopolis/spellcheck-github-actions@master
      name: Spellcheck