name: Spelling

on:
  pull_request:
  push:
    branches: [dev, master]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v2
    - name: Generate static files
      run: hugo
    - uses: rojopolis/spellcheck-github-actions@0.29.0
      name: Spellcheck