name: Spelling

on:
  pull_request:
  push:
    branches: [dev]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rojopolis/spellcheck-github-actions@0.21.1
      name: Spellcheck
      with:
        source_files: content/
        task_name: Markdown