name: Spelling

on:
  pull_request:

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v2
    - name: Generate static files
      run: hugo
    - uses: rojopolis/spellcheck-github-actions@0.29.0
      name: Spellcheck